services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: citoscan
      POSTGRES_USER: citoscan
      POSTGRES_PASSWORD: citoscan
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citoscan -d citoscan"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build: .
    environment:
      TF_ENABLE_ONEDNN_OPTS: "0"
      TF_CPP_MIN_LOG_LEVEL: "2"

      # DB interna
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/citoscan
      SPRING_DATASOURCE_USERNAME: citoscan
      SPRING_DATASOURCE_PASSWORD: citoscan
      SERVER_PORT: 8080

      APP_CORS_ALLOWED_ORIGINS: https://pf-2025b-pap3.it.itba.edu.ar

      PIPELINE_EXEC: http
      PIPELINE_URL: http://pipeline:5000
      PIPELINE_ROOT: /data/pipeline

      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-citoscanmailer@gmail.com}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-pbiuyxkibhnyejqe}

      APP_FRONTEND_URL: https://pf-2025b-pap3.it.itba.edu.ar

    volumes:
      - ./pipeline/resources/sessions:/data/pipeline/resources/sessions
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    depends_on:
      - backend
      - pipeline
    ports:
      - "80:80"

  pipeline:
    build:
      context: ./pipeline
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./pipeline/resources:/app/resources
      - ./pipeline/models:/app/models:ro
      - ./pipeline/configs:/app/configs:ro
      - ./pipeline/resources/sessions:/data/pipeline/resources/sessions
    expose:
      - "5000"
    depends_on:
      - db

volumes:
  db_data:
